name: CI Checks
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
#        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Configure Xvfb
        # https://www.electronjs.org/docs/tutorial/testing-on-headless-ci
        run: Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Install npm modules
        run: npm ci
      - name: Run CI checks
        run: npm test
