name: CI Checks
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
#        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install deps
        run: sudo apt-get -y install xorg xvfb gtk2-engines-pixbuf
      - name: NPM install
        run: npm ci
      - name: Run CI checks
        run: npm test
